export type EventCategory =
  | 'connection'
  | 'message'
  | 'group'
  | 'call'
  | 'appstate'
  | 'newsletter'
  | 'presence'
  | 'privacy'
  | 'misc'

export interface EventInfo {
  name: string
  goStruct: string
  description: string
  category: EventCategory
  fields: string[]
  notes: string[]
}

export const EVENTS: EventInfo[] = [
  {
    name: 'QR',
    goStruct: 'events.QR',
    description: 'QR code data for pairing — emitted when waiting for QR scan',
    category: 'connection',
    fields: ['Codes []string'],
    notes: ['First code lasts 60s, subsequent codes last 20s', 'Must call GetQRChannel() before Connect()'],
  },
  {
    name: 'PairSuccess',
    goStruct: 'events.PairSuccess',
    description: 'Successfully paired with a phone',
    category: 'connection',
    fields: ['ID types.JID', 'LID types.JID', 'BusinessName string', 'Platform string'],
    notes: ['Contains both phone-number JID and LID'],
  },
  {
    name: 'PairError',
    goStruct: 'events.PairError',
    description: 'Error during pairing process',
    category: 'connection',
    fields: ['ID types.JID', 'LID types.JID', 'BusinessName string', 'Platform string', 'Error error'],
    notes: [],
  },
  {
    name: 'Connected',
    goStruct: 'events.Connected',
    description: 'Successfully connected and authenticated',
    category: 'connection',
    fields: [],
    notes: ['Empty struct — no fields', 'Sent after successful handshake and login'],
  },
  {
    name: 'Disconnected',
    goStruct: 'events.Disconnected',
    description: 'Disconnected from WhatsApp servers',
    category: 'connection',
    fields: [],
    notes: ['Empty struct — check LoggedOut, StreamReplaced, ConnectFailure for specific reasons'],
  },
  {
    name: 'LoggedOut',
    goStruct: 'events.LoggedOut',
    description: 'Device was logged out (authentication revoked)',
    category: 'connection',
    fields: ['OnConnect bool', 'Reason ConnectFailureReason'],
    notes: [
      'Implements PermanentDisconnect interface',
      'OnConnect=true means logout detected during connection attempt',
      'Reason 401 = explicitly logged out, 403 = main device gone',
    ],
  },
  {
    name: 'StreamReplaced',
    goStruct: 'events.StreamReplaced',
    description: 'Another device took over the connection (conflict:replaced)',
    category: 'connection',
    fields: [],
    notes: ['Implements PermanentDisconnect', 'Empty struct — connection was replaced by another session'],
  },
  {
    name: 'StreamError',
    goStruct: 'events.StreamError',
    description: 'Stream-level error from WhatsApp servers',
    category: 'connection',
    fields: ['Code string', 'Raw *waBinary.Node'],
    notes: ['Code 515 triggers automatic reconnect', 'Code 401 triggers logout'],
  },
  {
    name: 'KeepAliveTimeout',
    goStruct: 'events.KeepAliveTimeout',
    description: 'Keepalive ping failed — connection may be stale',
    category: 'connection',
    fields: ['ErrorCount int', 'LastSuccess time.Time'],
    notes: ['ErrorCount tracks consecutive failures', 'After 3 minutes of failures, forces reconnect'],
  },
  {
    name: 'KeepAliveRestored',
    goStruct: 'events.KeepAliveRestored',
    description: 'Keepalive ping succeeded after previous failures',
    category: 'connection',
    fields: [],
    notes: ['Empty struct — signals recovery from keepalive timeout'],
  },
  {
    name: 'ConnectFailure',
    goStruct: 'events.ConnectFailure',
    description: 'Connection attempt failed',
    category: 'connection',
    fields: ['Reason ConnectFailureReason', 'Message string', 'Raw *waBinary.Node'],
    notes: [
      'Implements PermanentDisconnect',
      'Reason codes: 400=Generic, 401=LoggedOut, 402=TempBanned, 403=MainDeviceGone, 405=ClientOutdated, 409=BadUserAgent, 500=InternalServerError',
    ],
  },
  {
    name: 'TemporaryBan',
    goStruct: 'events.TemporaryBan',
    description: 'Account temporarily banned by WhatsApp',
    category: 'connection',
    fields: ['Code TempBanReason', 'Expire time.Duration'],
    notes: [
      'Implements PermanentDisconnect',
      'Codes: 101=SentToTooManyPeople, 102=BlockedByUsers, 103=CreatedTooManyGroups, 104=SentTooManySameMessage, 106=BroadcastList',
    ],
  },
  {
    name: 'ClientOutdated',
    goStruct: 'events.ClientOutdated',
    description: 'Client version is too old and must be updated',
    category: 'connection',
    fields: [],
    notes: ['Implements PermanentDisconnect', 'Update whatsmeow library version'],
  },
  {
    name: 'CATRefreshError',
    goStruct: 'events.CATRefreshError',
    description: 'Error refreshing CAT (Cross-Account Token)',
    category: 'connection',
    fields: ['Error error'],
    notes: ['Implements PermanentDisconnect'],
  },
  {
    name: 'QRScannedWithoutMultidevice',
    goStruct: 'events.QRScannedWithoutMultidevice',
    description: 'QR was scanned but phone does not support multi-device',
    category: 'connection',
    fields: [],
    notes: ['Empty struct'],
  },
  {
    name: 'ManualLoginReconnect',
    goStruct: 'events.ManualLoginReconnect',
    description: 'Server requested manual login reconnection',
    category: 'connection',
    fields: [],
    notes: ['Empty struct'],
  },
  {
    name: 'Message',
    goStruct: 'events.Message',
    description: 'Incoming message (text, media, interactive, etc.)',
    category: 'message',
    fields: [
      'Info types.MessageInfo',
      'Message *waE2E.Message',
      'IsEphemeral bool',
      'IsViewOnce bool',
      'IsViewOnceV2 bool',
      'IsViewOnceV2Extension bool',
      'IsDocumentWithCaption bool',
      'IsLottieSticker bool',
      'IsBotInvoke bool',
      'IsEdit bool',
      'SourceWebMsg *waWeb.WebMessageInfo',
      'UnavailableRequestID types.MessageID',
      'RetryCount int',
      'NewsletterMeta *NewsletterMessageMeta',
      'RawMessage *waE2E.Message',
    ],
    notes: [
      'Most important event — all incoming messages come through here',
      'Message.Info contains sender, chat, timestamp, push name',
      'Message.Message contains the actual content (check which field is non-nil)',
      'Boolean flags indicate FutureProofMessage unwrapping',
      'IsEdit=true when this is an edit of a previous message',
    ],
  },
  {
    name: 'FBMessage',
    goStruct: 'events.FBMessage',
    description: 'Incoming message via Meta/Facebook Messenger interop',
    category: 'message',
    fields: [
      'Info types.MessageInfo',
      'Message armadillo.MessageApplicationSub',
      'RetryCount int',
      'Transport *waMsgTransport.MessageTransport',
      'FBApplication *waMsgApplication.MessageApplication',
      'IGTransport *instamadilloTransportPayload.TransportPayload',
    ],
    notes: ['Used for cross-platform messaging (DMA interop)'],
  },
  {
    name: 'UndecryptableMessage',
    goStruct: 'events.UndecryptableMessage',
    description: 'Message that could not be decrypted',
    category: 'message',
    fields: [
      'Info types.MessageInfo',
      'IsUnavailable bool',
      'UnavailableType UnavailableType',
      'DecryptFailMode DecryptFailMode',
    ],
    notes: [
      'May occur when encryption keys are out of sync',
      'DecryptFailMode: "" (show) or "hide"',
      'UnavailableType: "" (unknown) or "view_once"',
    ],
  },
  {
    name: 'Receipt',
    goStruct: 'events.Receipt',
    description: 'Message delivery/read receipt',
    category: 'message',
    fields: [
      'MessageSource (embedded)',
      'MessageIDs []types.MessageID',
      'Timestamp time.Time',
      'Type types.ReceiptType',
      'MessageSender types.JID',
    ],
    notes: [
      'Types: "" (delivered), "read", "read-self", "played", "played-self", "sender", "retry", "server-error", "inactive", "peer_msg", "hist_sync"',
    ],
  },
  {
    name: 'MediaRetry',
    goStruct: 'events.MediaRetry',
    description: 'Response to a media re-download request',
    category: 'message',
    fields: [
      'Ciphertext []byte',
      'IV []byte',
      'Error *MediaRetryError',
      'Timestamp time.Time',
      'MessageID types.MessageID',
      'ChatID types.JID',
      'SenderID types.JID',
      'FromMe bool',
    ],
    notes: ['Decrypt with cli.DecryptMediaRetryNotification()', 'Uses AES-256-GCM'],
  },
  {
    name: 'HistorySync',
    goStruct: 'events.HistorySync',
    description: 'History sync data received during initial connection',
    category: 'message',
    fields: ['Data *waHistorySync.HistorySync'],
    notes: [
      'Contains chat history from the phone',
      'Process with cli.DownloadHistorySync() for media',
      'Used during initial device pairing to sync message history',
    ],
  },
  {
    name: 'ChatPresence',
    goStruct: 'events.ChatPresence',
    description: 'User is typing or recording audio in a chat',
    category: 'presence',
    fields: ['MessageSource (embedded)', 'State types.ChatPresence', 'Media types.ChatPresenceMedia'],
    notes: [
      'State: "composing" (typing) or "paused" (stopped typing)',
      'Media: "" (text) or "audio" (recording voice note)',
    ],
  },
  {
    name: 'Presence',
    goStruct: 'events.Presence',
    description: 'User online/offline presence update',
    category: 'presence',
    fields: ['From types.JID', 'Unavailable bool', 'LastSeen time.Time'],
    notes: ['Requires SubscribePresence() call first', 'Unavailable=true means offline'],
  },
  {
    name: 'JoinedGroup',
    goStruct: 'events.JoinedGroup',
    description: 'You were added to or joined a group',
    category: 'group',
    fields: [
      'Reason string',
      'Type string',
      'CreateKey types.MessageID',
      'Sender *types.JID',
      'SenderPN *types.JID',
      'Notify string',
      'GroupInfo (embedded types.GroupInfo)',
    ],
    notes: ['Contains full GroupInfo with participants, settings, etc.'],
  },
  {
    name: 'GroupInfo',
    goStruct: 'events.GroupInfo',
    description: 'Group metadata or membership changed',
    category: 'group',
    fields: [
      'JID types.JID',
      'Notify string',
      'Sender *types.JID',
      'SenderPN *types.JID',
      'Timestamp time.Time',
      'Name *types.GroupName',
      'Topic *types.GroupTopic',
      'Locked *types.GroupLocked',
      'Announce *types.GroupAnnounce',
      'Ephemeral *types.GroupEphemeral',
      'MembershipApprovalMode *types.GroupMembershipApprovalMode',
      'Delete *types.GroupDelete',
      'Link *types.GroupLinkChange',
      'Unlink *types.GroupLinkChange',
      'NewInviteLink *string',
      'Join []types.JID',
      'Leave []types.JID',
      'Promote []types.JID',
      'Demote []types.JID',
    ],
    notes: [
      'Check nil fields to determine what changed',
      'Join/Leave/Promote/Demote contain participant JIDs',
      'Name, Topic, Locked, Announce are group settings changes',
    ],
  },
  {
    name: 'Picture',
    goStruct: 'events.Picture',
    description: 'Profile or group picture changed',
    category: 'group',
    fields: ['JID types.JID', 'Author types.JID', 'Timestamp time.Time', 'Remove bool', 'PictureID string'],
    notes: ['Remove=true when picture was deleted', 'Use GetProfilePictureInfo() to fetch the new picture'],
  },
  {
    name: 'CallOffer',
    goStruct: 'events.CallOffer',
    description: 'Incoming call offer',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'CallRemoteMeta (embedded)', 'Data *waBinary.Node'],
    notes: [
      'BasicCallMeta: From, Timestamp, CallCreator, CallID, GroupJID',
      'CallRemoteMeta: RemotePlatform, RemoteVersion',
      'Use cli.RejectCall() to reject',
    ],
  },
  {
    name: 'CallAccept',
    goStruct: 'events.CallAccept',
    description: 'Call was accepted',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'CallRemoteMeta (embedded)', 'Data *waBinary.Node'],
    notes: [],
  },
  {
    name: 'CallPreAccept',
    goStruct: 'events.CallPreAccept',
    description: 'Pre-accept signal before full call acceptance',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'CallRemoteMeta (embedded)', 'Data *waBinary.Node'],
    notes: [],
  },
  {
    name: 'CallTransport',
    goStruct: 'events.CallTransport',
    description: 'Call transport/ICE candidate exchange',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'CallRemoteMeta (embedded)', 'Data *waBinary.Node'],
    notes: [],
  },
  {
    name: 'CallOfferNotice',
    goStruct: 'events.CallOfferNotice',
    description: 'Call offer notification with media type info',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'Media string', 'Type string', 'Data *waBinary.Node'],
    notes: ['Media indicates audio/video call type'],
  },
  {
    name: 'CallRelayLatency',
    goStruct: 'events.CallRelayLatency',
    description: 'Call relay latency measurement',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'Data *waBinary.Node'],
    notes: [],
  },
  {
    name: 'CallTerminate',
    goStruct: 'events.CallTerminate',
    description: 'Call was terminated/ended',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'Reason string', 'Data *waBinary.Node'],
    notes: ['Reason indicates why the call ended'],
  },
  {
    name: 'CallReject',
    goStruct: 'events.CallReject',
    description: 'Call was rejected by the recipient',
    category: 'call',
    fields: ['BasicCallMeta (embedded)', 'Data *waBinary.Node'],
    notes: [],
  },
  {
    name: 'UnknownCallEvent',
    goStruct: 'events.UnknownCallEvent',
    description: 'Unrecognized call event type',
    category: 'call',
    fields: ['Node *waBinary.Node'],
    notes: ['Fallback for new/unknown call event types'],
  },
  {
    name: 'Contact',
    goStruct: 'events.Contact',
    description: 'Contact information synced from app state',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.ContactAction', 'FromFullSync bool'],
    notes: ['FromFullSync=true during initial app state download'],
  },
  {
    name: 'PushName',
    goStruct: 'events.PushName',
    description: 'Contact push name (display name) changed',
    category: 'appstate',
    fields: ['JID types.JID', 'JIDAlt types.JID', 'Message *types.MessageInfo', 'OldPushName string', 'NewPushName string'],
    notes: ['Fired when a contact changes their WhatsApp display name'],
  },
  {
    name: 'BusinessName',
    goStruct: 'events.BusinessName',
    description: 'Business account name changed',
    category: 'appstate',
    fields: ['JID types.JID', 'Message *types.MessageInfo', 'OldBusinessName string', 'NewBusinessName string'],
    notes: [],
  },
  {
    name: 'Pin',
    goStruct: 'events.Pin',
    description: 'Chat was pinned or unpinned',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.PinAction', 'FromFullSync bool'],
    notes: ['Action contains Pin field (true=pinned, false=unpinned)'],
  },
  {
    name: 'Star',
    goStruct: 'events.Star',
    description: 'Message was starred or unstarred',
    category: 'appstate',
    fields: ['ChatJID types.JID', 'SenderJID types.JID', 'IsFromMe bool', 'MessageID string', 'Timestamp time.Time', 'Action *waSyncAction.StarAction', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'DeleteForMe',
    goStruct: 'events.DeleteForMe',
    description: 'Message deleted only for the current user',
    category: 'appstate',
    fields: ['ChatJID types.JID', 'SenderJID types.JID', 'IsFromMe bool', 'MessageID string', 'Timestamp time.Time', 'Action *waSyncAction.DeleteMessageForMeAction', 'FromFullSync bool'],
    notes: ['Different from message revoke — only affects local display'],
  },
  {
    name: 'Mute',
    goStruct: 'events.Mute',
    description: 'Chat was muted or unmuted',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.MuteAction', 'FromFullSync bool'],
    notes: ['Action.MuteEndTimestamp indicates when mute expires (0 = unmuted)'],
  },
  {
    name: 'Archive',
    goStruct: 'events.Archive',
    description: 'Chat was archived or unarchived',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.ArchiveChatAction', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'MarkChatAsRead',
    goStruct: 'events.MarkChatAsRead',
    description: 'Chat marked as read or unread',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.MarkChatAsReadAction', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'ClearChat',
    goStruct: 'events.ClearChat',
    description: 'Chat messages were cleared',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.ClearChatAction', 'FromFullSync bool', 'DeleteMedia bool'],
    notes: [],
  },
  {
    name: 'DeleteChat',
    goStruct: 'events.DeleteChat',
    description: 'Chat was deleted',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.DeleteChatAction', 'FromFullSync bool', 'DeleteMedia bool'],
    notes: [],
  },
  {
    name: 'PushNameSetting',
    goStruct: 'events.PushNameSetting',
    description: 'Own push name setting changed',
    category: 'appstate',
    fields: ['Timestamp time.Time', 'Action *waSyncAction.PushNameSetting', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'UnarchiveChatsSetting',
    goStruct: 'events.UnarchiveChatsSetting',
    description: 'Unarchive chats setting changed',
    category: 'appstate',
    fields: ['Timestamp time.Time', 'Action *waSyncAction.UnarchiveChatsSetting', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'UserStatusMute',
    goStruct: 'events.UserStatusMute',
    description: 'Status/story mute setting for a user',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Action *waSyncAction.UserStatusMuteAction', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'LabelEdit',
    goStruct: 'events.LabelEdit',
    description: 'Label was created, edited, or deleted',
    category: 'appstate',
    fields: ['Timestamp time.Time', 'LabelID string', 'Action *waSyncAction.LabelEditAction', 'FromFullSync bool'],
    notes: ['WhatsApp Business feature — labels for organizing chats'],
  },
  {
    name: 'LabelAssociationChat',
    goStruct: 'events.LabelAssociationChat',
    description: 'Label was associated with or removed from a chat',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'LabelID string', 'Action *waSyncAction.LabelAssociationAction', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'LabelAssociationMessage',
    goStruct: 'events.LabelAssociationMessage',
    description: 'Label was associated with or removed from a specific message',
    category: 'appstate',
    fields: ['JID types.JID', 'Timestamp time.Time', 'LabelID string', 'MessageID string', 'Action *waSyncAction.LabelAssociationAction', 'FromFullSync bool'],
    notes: [],
  },
  {
    name: 'AppStateSyncComplete',
    goStruct: 'events.AppStateSyncComplete',
    description: 'App state sync completed for a specific patch collection',
    category: 'appstate',
    fields: ['Name appstate.WAPatchName', 'Version uint64', 'Recovery bool'],
    notes: [
      'Patch names: critical_block, critical_unblock_low, regular_low, regular_high, regular',
      'Recovery=true during error recovery sync',
    ],
  },
  {
    name: 'AppStateSyncError',
    goStruct: 'events.AppStateSyncError',
    description: 'Error during app state sync',
    category: 'appstate',
    fields: ['Name appstate.WAPatchName', 'Error error', 'FullSync bool'],
    notes: ['FullSync=true indicates the error occurred during a full resync'],
  },
  {
    name: 'OfflineSyncPreview',
    goStruct: 'events.OfflineSyncPreview',
    description: 'Preview of pending offline sync data',
    category: 'misc',
    fields: ['Total int', 'AppDataChanges int', 'Messages int', 'Notifications int', 'Receipts int'],
    notes: ['Sent before actual offline data arrives'],
  },
  {
    name: 'OfflineSyncCompleted',
    goStruct: 'events.OfflineSyncCompleted',
    description: 'Offline sync finished processing',
    category: 'misc',
    fields: ['Count int'],
    notes: ['Count is total number of offline items processed'],
  },
  {
    name: 'IdentityChange',
    goStruct: 'events.IdentityChange',
    description: 'Contact encryption identity changed (safety number changed)',
    category: 'privacy',
    fields: ['JID types.JID', 'Timestamp time.Time', 'Implicit bool'],
    notes: ['Implicit=true when the identity change was detected indirectly'],
  },
  {
    name: 'PrivacySettings',
    goStruct: 'events.PrivacySettings',
    description: 'Privacy settings changed',
    category: 'privacy',
    fields: [
      'NewSettings types.PrivacySettings',
      'GroupAddChanged bool',
      'LastSeenChanged bool',
      'StatusChanged bool',
      'ProfileChanged bool',
      'ReadReceiptsChanged bool',
      'OnlineChanged bool',
      'CallAddChanged bool',
    ],
    notes: ['Check *Changed booleans to determine which settings were updated'],
  },
  {
    name: 'Blocklist',
    goStruct: 'events.Blocklist',
    description: 'Blocklist was modified',
    category: 'privacy',
    fields: ['Action BlocklistAction', 'DHash string', 'PrevDHash string', 'Changes []BlocklistChange'],
    notes: [
      'Action: "" (default/full list) or "modify" (incremental)',
      'BlocklistChange contains JID and Action ("block" or "unblock")',
    ],
  },
  {
    name: 'UserAbout',
    goStruct: 'events.UserAbout',
    description: 'User about/status text changed',
    category: 'privacy',
    fields: ['JID types.JID', 'Status string', 'Timestamp time.Time'],
    notes: [],
  },
  {
    name: 'NewsletterJoin',
    goStruct: 'events.NewsletterJoin',
    description: 'Joined a newsletter/channel',
    category: 'newsletter',
    fields: ['NewsletterMetadata (embedded types.NewsletterMetadata)'],
    notes: ['Contains full newsletter metadata'],
  },
  {
    name: 'NewsletterLeave',
    goStruct: 'events.NewsletterLeave',
    description: 'Left a newsletter/channel',
    category: 'newsletter',
    fields: ['ID types.JID', 'Role types.NewsletterRole'],
    notes: [],
  },
  {
    name: 'NewsletterMuteChange',
    goStruct: 'events.NewsletterMuteChange',
    description: 'Newsletter mute setting changed',
    category: 'newsletter',
    fields: ['ID types.JID', 'Mute types.NewsletterMuteState'],
    notes: [],
  },
  {
    name: 'NewsletterLiveUpdate',
    goStruct: 'events.NewsletterLiveUpdate',
    description: 'Real-time newsletter message update',
    category: 'newsletter',
    fields: ['JID types.JID', 'Time time.Time', 'Messages []*types.NewsletterMessage'],
    notes: ['Requires SubscribeLiveUpdates() call first'],
  },
]

export function getEventsByCategory(category: EventCategory): EventInfo[] {
  return EVENTS.filter((e) => e.category === category)
}

export function getEventByName(name: string): EventInfo | undefined {
  return EVENTS.find((e) => e.name.toLowerCase() === name.toLowerCase() || e.goStruct.toLowerCase() === name.toLowerCase())
}

export function searchEvents(query: string): EventInfo[] {
  const q = query.toLowerCase()
  return EVENTS.filter(
    (e) =>
      e.name.toLowerCase().includes(q) ||
      e.goStruct.toLowerCase().includes(q) ||
      e.description.toLowerCase().includes(q) ||
      e.fields.some((f) => f.toLowerCase().includes(q)) ||
      e.notes.some((n) => n.toLowerCase().includes(q)),
  )
}
